spring:
  application:
    name: your-mode-backend
  datasource:
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&useSSL=true&serverSslCert=classpath:mysql-ssl-ca.pem
  data:
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD:}
      ssl: ${REDIS_SSL:false}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
  security:
    user:
      name: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION:604800000}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION:3600000}

springdoc:
  swagger-ui:
    path: /docs
    multipart:
      enabled: true
    tags-sorter: alpha
  api-docs:
    path: /api-docs

server:
  port: ${SERVER_PORT:8080}
  ssl:
    enabled: true
    key-store: ${SSL_KEYSTORE_PATH}
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-store-type: ${SSL_KEYSTORE_TYPE:PKCS12}
    key-alias: ${SSL_KEY_ALIAS}
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION:ap-northeast-2}
    s3:
      bucket: ${AWS_S3_BUCKET}
      endpoint: ${AWS_S3_ENDPOINT:}

logging:
  level:
    com.yourmode.yourmodebackend: ${LOG_LEVEL:INFO}
    org.springframework.security: ${SECURITY_LOG_LEVEL:WARN}
    org.hibernate.SQL: ${SQL_LOG_LEVEL:WARN}
    org.hibernate.type.descriptor.sql.BasicBinder: ${SQL_PARAM_LOG_LEVEL:WARN}
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ${LOG_FILE_PATH:/var/log/your-mode/application.log}
    max-size: ${LOG_MAX_SIZE:10MB}
    max-history: ${LOG_MAX_HISTORY:30}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  health:
    redis:
      enabled: true
    db:
      enabled: true

redirect:
  new-user: ${FRONTEND_URL}/signup/additional-info
  existing-user: ${FRONTEND_URL}

kakao:
  redirect-uri: ${BACKEND_URL}/api/auth/oauth2/kakao/callback
  client-id: ${KAKAO_CLIENT_ID}

coolsms:
  fromnumber: ${COOLSMS_FROM_NUMBER}
  apisecret: ${COOLSMS_API_SECRET}
  apikey: ${COOLSMS_API_KEY}

# 프로덕션 환경 전용 설정
production:
  monitoring:
    enabled: true
    metrics:
      enabled: true
  security:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:https://yourmode.com,https://www.yourmode.com}
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true
    rate-limit:
      enabled: true
      requests-per-minute: ${RATE_LIMIT_RPM:100}
