name: Build and Test on Develop

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create application-local.properties
        run: |
          cd src/main/resources
          echo "${{ secrets.APPLICATION_DEV }}" > application-dev.properties

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle using 'local' profile
        run: ./gradlew build -x test -Dspring.profiles.active=local

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload build artifacts to S3
        run: aws s3 cp build/libs/yourmode-0.0.1-SNAPSHOT.jar s3://${{ secrets.S3_BUCKET }}/${{ secrets.S3_PATH }}/ --acl public-read
